### ISSUE TITLE
Para considerar

### ISSUE THREAD

**Issue by atarico** [atarico/grupo-4#20]
El código se ve excelente la experiencia de uso es buena salvo por el molesto "beep" (yo lo sacaría, pero es solo una sugerencia, el sistema es de ustedes y si les parece una buena incorporación dejenlo). 
Por ahí sería bueno que en vez de ponerle una fecha de inicio, marcar una fecha de finalizacion y que tome la fecha actual como la fecha de inicio del proyecto.

**Comment by Matt-Py-GH** [comment]
Buenas tardes, muchas gracias por el comentario, mi compañera opina lo mismo sobre el beep, son dos contra uno por ende lo voy a eliminar. Tengo una duda sobre la segunda sugerencia, te referis al atributo de fechaIncio del proyecto? Es decir querés que ese atributo sea siempre la fecha misma que se crea el proyecto o sea Datetime.Today y se agregue una fecha de finalización estimada y esa sea cargada por el usuario? Muchas gracias y espero se entienda la duda.
